# Generated by Django 3.0 on 2023-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Birthdate', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
    ]
